### ISSUE TITLE
Error trying to `make debian` on PureOS (debian based)

### ISSUE THREAD

**Issue by bingen** [open-eid/chrome-token-signing#169]
I get the following errors:
```
# wildcard will resolve to an empty string with a missing file
# so that OSX will not run with xvfb
/usr/bin/xvfb-run python host-test/pipe-test.py -v
test_empty_json (__main__.TestHostPipe) ... Unsupported platform: linux
ERROR
test_inconsistent_origin (__main__.TestHostPipe) ... Unsupported platform: linux
ERROR
test_plain_string (__main__.TestHostPipe) ... Unsupported platform: linux
ERROR
test_random_string (__main__.TestHostPipe) ... Unsupported platform: linux
ERROR
test_utopic_length (__main__.TestHostPipe) ... Unsupported platform: linux
ERROR
test_version_file_origin (__main__.TestHostPipe) ... Unsupported platform: linux
ERROR
test_version_http_origin (__main__.TestHostPipe) ... Unsupported platform: linux
ERROR
test_version_https (__main__.TestHostPipe) ... Unsupported platform: linux
ERROR
test_version_invalid_origin (__main__.TestHostPipe) ... Unsupported platform: linux
ERROR
test_version_no_nonce (__main__.TestHostPipe) ... Unsupported platform: linux
ERROR
test_version_no_origin (__main__.TestHostPipe) ... Unsupported platform: linux
ERROR

======================================================================
ERROR: test_empty_json (__main__.TestHostPipe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "host-test/pipe-test.py", line 51, in setUp
    self.p = subprocess.Popen(testconf.get_exe(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=should_close_fds, stderr=None)
  File "/home/bingen/Downloads/e-residency/chrome-token-signing/host-test/testconf.py", line 34, in get_exe
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_inconsistent_origin (__main__.TestHostPipe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "host-test/pipe-test.py", line 51, in setUp
    self.p = subprocess.Popen(testconf.get_exe(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=should_close_fds, stderr=None)
  File "/home/bingen/Downloads/e-residency/chrome-token-signing/host-test/testconf.py", line 34, in get_exe
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_plain_string (__main__.TestHostPipe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "host-test/pipe-test.py", line 51, in setUp
    self.p = subprocess.Popen(testconf.get_exe(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=should_close_fds, stderr=None)
  File "/home/bingen/Downloads/e-residency/chrome-token-signing/host-test/testconf.py", line 34, in get_exe
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_random_string (__main__.TestHostPipe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "host-test/pipe-test.py", line 51, in setUp
    self.p = subprocess.Popen(testconf.get_exe(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=should_close_fds, stderr=None)
  File "/home/bingen/Downloads/e-residency/chrome-token-signing/host-test/testconf.py", line 34, in get_exe
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_utopic_length (__main__.TestHostPipe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "host-test/pipe-test.py", line 51, in setUp
    self.p = subprocess.Popen(testconf.get_exe(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=should_close_fds, stderr=None)
  File "/home/bingen/Downloads/e-residency/chrome-token-signing/host-test/testconf.py", line 34, in get_exe
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_version_file_origin (__main__.TestHostPipe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "host-test/pipe-test.py", line 51, in setUp
    self.p = subprocess.Popen(testconf.get_exe(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=should_close_fds, stderr=None)
  File "/home/bingen/Downloads/e-residency/chrome-token-signing/host-test/testconf.py", line 34, in get_exe
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_version_http_origin (__main__.TestHostPipe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "host-test/pipe-test.py", line 51, in setUp
    self.p = subprocess.Popen(testconf.get_exe(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=should_close_fds, stderr=None)
  File "/home/bingen/Downloads/e-residency/chrome-token-signing/host-test/testconf.py", line 34, in get_exe
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_version_https (__main__.TestHostPipe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "host-test/pipe-test.py", line 51, in setUp
    self.p = subprocess.Popen(testconf.get_exe(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=should_close_fds, stderr=None)
  File "/home/bingen/Downloads/e-residency/chrome-token-signing/host-test/testconf.py", line 34, in get_exe
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_version_invalid_origin (__main__.TestHostPipe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "host-test/pipe-test.py", line 51, in setUp
    self.p = subprocess.Popen(testconf.get_exe(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=should_close_fds, stderr=None)
  File "/home/bingen/Downloads/e-residency/chrome-token-signing/host-test/testconf.py", line 34, in get_exe
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_version_no_nonce (__main__.TestHostPipe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "host-test/pipe-test.py", line 51, in setUp
    self.p = subprocess.Popen(testconf.get_exe(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=should_close_fds, stderr=None)
  File "/home/bingen/Downloads/e-residency/chrome-token-signing/host-test/testconf.py", line 34, in get_exe
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_version_no_origin (__main__.TestHostPipe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "host-test/pipe-test.py", line 51, in setUp
    self.p = subprocess.Popen(testconf.get_exe(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=should_close_fds, stderr=None)
  File "/home/bingen/Downloads/e-residency/chrome-token-signing/host-test/testconf.py", line 34, in get_exe
    sys.exit(1)
SystemExit: 1

----------------------------------------------------------------------
Ran 11 tests in 0.002s

FAILED (errors=11)
make[2]: *** [GNUmakefile:42: test] Error 1
make[2]: Leaving directory '/home/bingen/Downloads/e-residency/chrome-token-signing'
dh_auto_test: make -j4 test returned exit code 2
make[1]: *** [debian/rules:9: build] Error 2
make[1]: Leaving directory '/home/bingen/Downloads/e-residency/chrome-token-signing'
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
make: *** [GNUmakefile:40: debian] Error 2
```

**Comment by metsma** [comment]
What happens when you change 
https://github.com/open-eid/chrome-token-signing/blob/master/host-test/testconf.py#L25
from "linux2" to "linux"?

**Comment by metsma** [comment]
Closing: no feedback for while, reopen when needed
